# namespace.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: vpn
  labels:
    routed-gateway: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: pod-gateway
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vpn-container-role
  namespace: vpn
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - events
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - pods/log
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vpn-container-rolebinding
  namespace: vpn
subjects:
  - kind: ServiceAccount
    name: default
    namespace: vpn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vpn-container-role
